try{
    let val=convert(4);
    console.log("converted");
}
catch(err){
    console.log("error detected");
    console.log(err);
}

console.log("still running");